printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: true
trailingComma: es5
overrides:
  - files: "*.jsx"
    options:
      printWidth: 80
      tabWidth: 2
      singleQuote: true
      jsxSingleQuote: true
